### PR TITLE
Modify footer to take value of source repo from /api/systemInfo inste…

### LINKED ISSUE #2: Modify footer to take value of source repo from /api/systemInfo instead of being hardcoded
Relies on #1 

The footer has a link to the source repo:
Image

The word GitHub links currently to: https://github.com/ucsb-cs156-s22/s22-4pm-courses

Another issue is moving this value to /api/systemInfo. Change the footer component so that it gets the value of the URL for the source repo from /api/systeminfo

The navbar also uses systemInfo so you can see how it is handled there.

Be sure to modify tests, and storybook entries accordingly.

Also modify the fixtures for systemInfo to contain the new example values for sourceRepo

### PR DESCRIPTION
**Pull request by drikdrok**
…ad of being hardcoded

Resolves #2

### CODE REVIEW

**Review by tallyhawley — CHANGES_REQUESTED** [review]
Could you fix these failing code coverage/mutation testing CIs?

**Comment by pconrad** [comment]
@drikdrok Here's how you can look up what's wrong:

image


It appears to be entirely OptionalChaining

This is one mutation that we generally allow overriding, since it's awfully tedious to check every case.  That looks like this:

```
// Stryker disable OptionalChaining 

code that has the optional chaining

// Stryker enable OptionalChaining
```

You have to be a little careful that these comments are on a line by themselves, so they have to be in a "javascript" block, not a JSX block.   So 


```
export default function Footer(systemInfo) {
  // Stryker disable OptionalChaining 
  return (
```
and

```
 </div>
  );
 // Stryker enable OptionalChaining
}
```

NOT: 

```
{ //  Stryker disable OptionalChaining  }
<a
        data-testid="footer-source-code-link"
        href={systemInfo?.systemInfo?.sourceRepo ? systemInfo?.systemInfo?.sourceRepo : "https://github.com/ucsb-cs156-f22/f22-5pm-courses" }
        target="_blank"
        rel="noopener noreferrer"
      >
 {  // Stryker enable OptionalChaining }
 ```

You could try this: it might work, but I had trouble with it.  If it works, it's the ideal solution.

```
{ 
  //  Stryker disable OptionalChaining 
}
<a
        data-testid="footer-source-code-link"
        href={systemInfo?.systemInfo?.sourceRepo ? systemInfo?.systemInfo?.sourceRepo : "https://github.com/ucsb-cs156-f22/f22-5pm-courses" }
        target="_blank"
        rel="noopener noreferrer"
      >
 {  
  // Stryker enable OptionalChaining 
 } 
 ```

**Comment by pconrad** [comment]
Looks like this still needs one fix to the mutation testing---this is a legit case where a test is really needed.

image

The test you have:

image

covers the case where systemInfo is NOT defined.  What you need is another test where you mock the /api/systemInfo endpoint with a value for courseRepo and then assert that the value shows up.

**Review by tallyhawley — CHANGES_REQUESTED** [review]
We’re still seeing red on frontend mutation testing. Could you please get that coverage up to 100

**Review by pconrad — APPROVED** [review]
LGTM!

**Pull request merged**
