### PR TITLE
IH: Add query & controller for course-over-time search

### LINKED ISSUE #26: Add service which gets course sections within given quarter range from MongoDB database
Make a service, similar to the UCSBCurriculumService, but instead of doing API calls, do MongoDB queries. Write tests. You need a method that takes a start quarter, end quarter, and a course id, and returns a list of ConvertedSections.

Requirements:
- [ ] There is a new service, `CourseOverTimeService` (or another name, as long as it's consistent)
- [ ] This service makes MongoDB queries
- [ ] This service has a method which takes a start quarter, end quarter, and course ID, and returns a list of ConvertedSections corresponding to *every* section corresponding to that course ID such that the section occurred between the given start quarter and end quarter (inclusive)
- [ ] There are appropriate tests on the backend
- [ ] We should have 100% mutation test strength & jacoco coverage

### LINKED ISSUE #27: Add a backend controller method to get courses over time
Relies on #26 

Write a backend controller method (unauthenticated GET) that takes a start quarter, end quarter, and a course id, and returns a list of Converted Sections. This is just wrapping a backend controller route around the service developed in #26.

Requirements:
- [ ] There is a new controller on the backend corresponding to the new backend service added in #26.
- [ ] This controller has a `GET` method which takes a start quarter, end quarter, and course ID, and returns a list of sections with that course ID which occurred within the given quarter range. This must use the previously added service.
- [ ] There are sufficient tests for this controller.

### PR DESCRIPTION
**Pull request by tallyhawley**
Closes #26 
Closes #27 

This adds a MongoDB query to the `ConvertedSectionCollection` which returns a list of `ConvertedSection`s given a start quarter, an end quarter, and a course ID. It uses Mongo's GTE and LTE (>= and <=) for the quarter range, and regex for the course ID (to get all courses which start with the given ID, so as to include courses with multiple lectures).

This also adds a new controller, the `CourseOverTimeController` which calls the new query. Its only method, `search()`, accessed using the `/api/public/courseovertime/search` endpoint, takes a `startQtr`, `endQtr`, `subjectArea`, and `courseNumber`. All of these are `String`s.

`courseNumber` can contain a letter suffix, or not. If `courseNumber` does not contain a suffix, but the associated courses have suffixes (i.e. `courseNumber = 130` but the available courses are `CMPSC 130A` and `CMPSC 130B`), we will return all courses with the given number and *any* suffix. This is facilitated by the new `makeFormattedCourseId` function, which takes a `subjectArea` and `courseNumber` and returns a properly-formatted `courseId` string, taking into account the possibility of a suffix.

Tested on Heroku using the Swagger UI. The MongoDB database currently only contains S22 ANTH & CMPSC courses, so I tested using CMPSC 130A and CMPSC 24.

Controller endpoint on Swagger (on Heroku) using a course with a suffix (CMPSC 130A):
image

Response (first lines):
image

Using a course without a suffix (CMPSC 24):
image

Response (first lines):
image

### CODE REVIEW

**Review by ethanlee556 — DISMISSED** [review]
lgtm

**Review by pconrad — CHANGES_REQUESTED** [review]
I think this might be easier to test if you were to implement a controller method that invoked this query.

That way, we could try it out using swagger.

Could you give that a try?

**Review by liamjet — APPROVED** [review]
LGTM

**Comment by tallyhawley** [comment]
After looking more closely at the API calls made in Ethan's frontend form, I'm going to modify the endpoint to take a suffix separately from the course number.

**Review by pconrad — APPROVED** [review]
LGTM!

**Pull request merged**
